language: go
go:
  - 1.16.x

before_install:
  - go get -u github.com/mattn/goveralls
install: make

script:
  - COVERAGE="-covermode=count -coverprofile=coverage.out" make test
  - goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN
